title: <p align="center"> Shilpa Angadi </p>

logo: "/assets/img/circle-cropped.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Shilpa_Angadi_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shilpa-443b3516b/">LinkedIn</a> |
  <a href="https://github.com/RavikiranShilpa">GitHub</a> 
  </p> 
  
  <p align="justify">
  <br>
  I am currently working as  Data Scientist at Beekin  with  focus on NLP and Deep Learning research,while previously I have dealt with credit risk and real estate domain.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
